<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace modernkernel\slugify;

use yii\helpers\Html;
use yii\widgets\InputWidget;

/**
 * Class Slugify
 * @package modernkernel\slugify
 */
class Slugify extends InputWidget
{

    public $source='';
    //public $clientOptions=[];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!isset($this->options['class'])) {
            $this->options['class'] = 'form-control';
        }


    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        if ($this->hasModel()) {
            echo Html::activeTextInput($this->model, $this->attribute, $this->options);
        } else {
            echo Html::textInput($this->name, $this->value, $this->options);
        }
        $this->registerJS();
    }

    /**
     * Registers plugin and the related events
     */
    protected function registerPlugin()
    {
        $view = $this->getView();
        SlugifyAsset::register($view);
    }

    /**
     * Register JS
     */
    protected function registerJS()
    {
        $this->registerPlugin();
        $id=$this->options['id'];
        $js='$("#'.$id.'").slugify("'.$this->source.'")';
        $this->view->registerJs($js);

    }

} 
